version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-container
    environment:
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: MyS@ql#2025_Secure!
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: